### PR TITLE
Change Calendar.HOUR to Calendar.HOUR_OF_DAY

### PR DESCRIPTION
**Pull request by douglasjunior**
Because in regions where it works with 24h, using `cal.set(Calendar.HOUR, 0)` can happen to set as 12AM instead of 12PM.

Like this:
```
I/System.out﹕ Tue Aug 25 12:00:00 BRT 2015
```

The correct would be:
```
I/System.out﹕ Tue Aug 25 00:00:00 BRT 2015
```

### CODE REVIEW

**Comment by androiddev-smartside** [comment]
This is looks very useful, any hints on why is has not yet been accepted?

**Comment by douglasjunior** [comment]
I do not know what plans the owner. But to solve here, I created a `CustomDateValidator`.

See https://gist.github.com/douglasjunior/5bf82f11f5f006a4b5b9

**Comment by androiddev-smartside** [comment]
Muito bom, obrigado por compartilhar.

**Comment by douglasjunior** [comment]
Sorry, I had a problem in the previous branch.

New pull request https://github.com/inmite/android-validation-komensky/pull/37

**Pull request closed without merging**
